---
- hosts: all
  become: yes
  become_method: su
  tasks:
  - name: install servies on Debian servers
    apt:
      name:
         - apache2
         - nginx
         - bind9
         - mariadb-server
      state: latest
    when: ansible_os_family=="Debian"
  - name: install servies on Redhat servers
    yum:
      name:
        - httpd
        - nginx
        - bind
        - mariadb
      state: latest
    when: ansible_os_family=="RedHat"
  - name: install services on FreeBSD servers
    pkgng:
      name:
        - apache24
        - nginx
        - bind916-9.16.19 
        - mariadb105-server-10.5.11 
    when: ansible_os_family=="FreeBSD"
